config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'events#index'
  devise_for :users,controllers:{
    registrations: "users/registrations",
    sessions: 'users/sessions',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    post 'users/guest_sign_in', to:'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to:'users/sessions#guest_admin_sign_in'
  end
  resources :users do
    resources :mylocations, only:[:new, :create, :destroy]
    member do
      get :mypage
      get :posts_index
    end
  end
  resources :events do
    collection do
      get '/hashtag/:name', to:'events#hashtag'
      get 'search', to:'events#search'
    end
  end
  resources :comments, only:[:index, :create, :destroy]
  resources :favorites, only:[:create,:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :user_id, uniqueness: { scope: :event_id }
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @event = Event.find(params[:event_id])
    @favorite = current_user.favorites.new(event_id: params[:event_id])
    respond_to do |format|
      if @favorite.save
        format.js
      else
        format.html { redirect_to @even, notice:"お気に入りできませんでした" }
      end
    end
  end

  def destroy
    @event = Event.find(params[:event_id])
    @favorite = Favorite.find(params[:id])
    respond_to do |format|
      if @favorite.destroy
        @favorite = nil
        format.js
      else
        format.html { redirect_to @event, notice: "削除できませんでした"}
      end
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if user_signed_in? %>
  <% if favorite.present? %>
    <%= link_to favorite_path(id: favorite.id, event_id: event.id), method: :delete , remote: true, class:"like" do %>
      <%= image_tag 'like.png' %>
      <span><%= event.favorites.count %></span>
    <% end %>

  <% else %>
    <%= link_to favorites_path(event_id: event.id), method: :post , remote: true, class:"dislike" do %>
      <%= image_tag 'dislike.png' %>
      <span><%= event.favorites.count %></span>
    <% end %>
  <% end %>
<% else %>
  <span class="like"><%= image_tag 'like.png' %><%= event.favorites.count %></span>
<% end %>

app/views/favorites/create.js.erb
$("#favorite_area").html("<%= j(render 'favorites/favorite', { favorite: @favorite, event: @event })%>");

app/views/favorites/destroy.js.erb
$("#favorite_area").html("<%= j(render 'favorites/favorite', { favorite: @favorite, event: @event })%>");