config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'events#index'
  devise_for :users,controllers:{
    registrations: "users/registrations",
    sessions: 'users/sessions',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    post 'users/guest_sign_in', to:'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to:'users/sessions#guest_admin_sign_in'
  end
  resources :users do
    resources :mylocations, only:[:new, :create, :destroy]
    member do
      get :mypage
      get :posts_index
    end
  end
  resources :events do
    collection do
      get '/hashtag/:name', to:'events#hashtag'
      get 'search', to:'events#search'
    end
  end
  resources :comments, only:[:index, :create, :destroy]
  resources :favorites, only:[:create,:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, { presence: true,
                    format: { with: VALID_EMAIL_REGEX}}

  has_many :events
  has_many :favorites, dependent: :destroy
  has_many :favorite_events, through: :favorites, source: :event
  has_many :comments, dependent: :destroy
  has_many :mylocations, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :omniauthable, omniauth_providers: %i(google)

  THUMBNAIL_SIZE = [100, 100]
  mount_uploader :image, ImageUploader

  def self.create_unique_string
    SecureRandom.uuid
  end

  def self.guest
    find_or_create_by!(email:"guest@guest.com") do |user|
      user.name = "guest"
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def self.guest_admin
    find_or_create_by!(email:"guest_admin@guest.com") do |user|
      user.name = "guest_admin"
      user.password = SecureRandom.urlsafe_base64
      user.admin = true
    end
  end

  def self.find_for_google(auth)
    user = User.find_by(email: auth.info.email)
    unless user
      user = User.new(name: auth.info.name,
                      email: auth.info.email,
                      provider: auth.provider,
                      uid: auth.uid,
                      password: Devise.friendly_token[0,20],
                    )
    end
    user.save
    user
  end

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google
    @user = User.find_for_google(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "google") if is_navigational_format?
    else
      session['devise.google_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_account_update_params, only:[:update]

  def build_resource(hash={})
    hash[:uid] = User.create_unique_string
    super
  end

  private
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys:[:name,:image,:image_cache])
  end

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice:'ゲストユーザ(一般)としてログインしました'
  end

  def guest_admin_sign_in
    user = User.guest_admin
    sign_in user
    redirect_to root_path, notice:'ゲストユーザ(管理者)としてログインしました'
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def mypage
    @events = current_user.favorite_events.includes(:categories).all
    gon.events = @events.map { |event | {
      'event': event,
      'categories': event.categories.pluck(:name),
      'date': "#{event.start_date.strftime("%Y年%m月%d日")} ~ #{event.end_date.strftime("%Y年%m月%d日")}",
      'current_user':current_user.id
      }
    }
    gon.user_id = current_user.id
  end

  def posts_index
    @events = current_user.events.includes(:categories).all.order(created_at:"DESC")
    gon.events = @events.map { |event | {
      'event': event,
      'categories': event.categories.pluck(:name),
      'date': "#{event.start_date.strftime("%Y年%m月%d日")} ~ #{event.end_date.strftime("%Y年%m月%d日")}",
      'current_user': current_user.id
      }
    }
    gon.user_id = current_user.id
    render 'mypage'
  end
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/mypage.html.erb
<div class="map-wrapper p-3">
  <div class="result-message p-3">
    <% if action_name == 'posts_index' %>
      <h1><%= current_user.name %>さんが投稿したイベントを表示</h1>
    <% else %>
      <h1><%= current_user.name %>さんが気になったイベントを表示</h1>
    <% end %>
  </div>
  <div class="">
    <%= link_to t('view.mylocation.posts'), posts_index_user_path(current_user.id),class:"myindex-btn mr-3 shadow" %><%= link_to t('view.mylocation.favorites'), mypage_user_path(current_user.id) , class:"myindex-btn shadow" %>
  </div>
  <div class="container-fluid my-3 px-3">
    <div class="row">
      <div class="col-sm-12 col-md-9 space-cols">
        <div id="mapid" class="map-mypage">
        </div>
      </div>
      <div class="col-sm-12 col-md-3 space-cols">
        <div class="module p-2">
          <h6><%= t('view.mylocation.index')%></h6>
          <% if current_user.mylocations.present? %>
            <p class="note">※クリックすると地図が遷移します</p>
          <% else %>
            <p class="note">※マイロケーションを登録するとここに表示されます</p>
          <% end %>
          <% if current_user.mylocations %>
            <div class="myloc-index">
              <% current_user.mylocations.each do |ml| %>
                <span data-lat="<%= ml.my_latitude %>" data-lng="<%= ml.my_longitude %>" data-name="<%= ml.name %>" class="gotoMyloc mb-2 mr-2 py-1 pl-1 pr-5">
                  <object class"delete-myloc">
                    <%= link_to user_mylocation_path(current_user.id, ml.id),data:{confirm:t('view.mylocation.delete?')},method: :delete do %>
                     <i class="fas fa-times-circle"></i>
                    <% end %>
                  </object>
                  <%= ml.name %><br>
                  <p><%= ml.my_address %></p>
                </span><br>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="mx-0">
  <div class="m-3">
    <% if action_name == 'posts_index' %>
      <h2>投稿したイベント</h2>
    <% else %>
      <h2>気になったイベント一覧</h2>
    <% end %>
    <hr>
  </div>
  <div class="event-container">
    <div class="event-row">
      <% if @events.present? %>
       <% @events.each do |event| %>
         <div class="event-card shadow">
           <%= link_to event_path(event.id),remote:true, data:{lat:event.latitude,lon: event.longitude} do %>
           <p class="card-title"><%= event.title %></p>
           <ul>
             <li><i class="far fa-calendar-alt"></i><%= l event.start_date, format: :day %>~<%= l event.end_date, format: :day %> </li>
             <li><i class="fas fa-map-marker-alt"></i><%= event.location %></li>
             <% event.categories.each do |cat| %>
              <span class="category"><%= cat.name %></span>
             <% end %>
           </ul>
           <% end %>
         </div>
       <% end %>
      <% else %>
       <p>投稿したイベントはありません</p>
      <% end %>
    </div>
  </div>
</div>

<div id="mask" class="hidden"></div>

<div id="new_event_modal" class="hidden"></div>
<div id="new_mylocation_modal" class="hidden"></div>
<div id="edit_event_modal" class="hidden"></div>
<div id="show_event_modal" class="hidden"></div>

<% if action_name == 'create' || action_name == 'update' %>
  <%= javascript_include_tag 'event_show' %>
<% else %>
  <%= javascript_include_tag 'mypage' %>
<% end %>

app/views/users/show.html.erb
<h1><%= current_user.name %>さんのマイページ</h1>

<div id="mapid" class="map-mypage"></div>


<div id="mask" class="hidden"></div>

<div id="new_event_modal" class="hidden"></div>

<% if action_name == 'create' || action_name == 'update' %>
  <%= javascript_include_tag 'event_show' %>
<% else %>
  <%= javascript_include_tag 'mypage' %>
<% end %>