config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'events#index'
  devise_for :users,controllers:{
    registrations: "users/registrations",
    sessions: 'users/sessions',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    post 'users/guest_sign_in', to:'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to:'users/sessions#guest_admin_sign_in'
  end
  resources :users do
    resources :mylocations, only:[:new, :create, :destroy]
    member do
      get :mypage
      get :posts_index
    end
  end
  resources :events do
    collection do
      get '/hashtag/:name', to:'events#hashtag'
      get 'search', to:'events#search'
    end
  end
  resources :comments, only:[:index, :create, :destroy]
  resources :favorites, only:[:create,:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :categorizings, dependent: :destroy
  has_many :categories, through: :categorizings, source: :category
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :comments, dependent: :destroy
  has_many :hashtagings, dependent: :destroy
  has_many :hashtags, through: :hashtagings, source: :hashtag

  with_options presence: true do
    validates :title
    validates :description
    validates :start_date
    validates :end_date
    validates :location
    validates :latitude
    validates :longitude
    validates :categories
  end

  validate :start_end_check

  THUMBNAIL_SIZE = [500, 500]
  mount_uploader :image, ImageUploader

  def self.ransackable_attributes(auth_object = nil)
    %w[start_date end_date]
  end

  def start_end_check
    if self.start_date && self.end_date
      errors.add(:end_date, "は開始日より後になるよう設定してください") if self.start_date > self.end_date
    end
  end

  after_create do
    event = Event.find_by(id: self.id)
    hashtags = self.description.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    event.hashtags = []
    hashtags.uniq.map do |hashtag|
      tag = Hashtag.find_or_create_by(name: hashtag.delete('/[#＃]/'))
      event.hashtags << tag
    end

  end

  before_update do
    event = Event.find_by(id: self.id)
    event.hashtags.clear
    hashtags = self.description.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      tag = Hashtag.find_or_create_by(name: hashtag.delete('/[#＃]/'))
      event.hashtags << tag
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :set_event, only: %i[show edit update destroy]

  def index
    @q = Event.ransack(params[:q])
    @categories = Category.all
    @events = Event.includes(:categories).where("start_date <= ?", Time.now).where("end_date >= ?", Time.now)
    gon.events = @events.map do | event |
       {
         'event':event,
         'categories':event.categories.pluck(:name),
         'date':"#{event.start_date.strftime("%Y年%m月%d日")} ~ #{event.end_date.strftime("%Y年%m月%d日")}",
         'countdate':"#{((event.end_date - Time.now)/60/60/24).ceil}"
       }
     end

    @day_searched = Time.now
    @hashtags = Hashtag.last(10).pluck(:name)
  end

  def search
    @q = Event.ransack(params[:q])
    @categories = Category.all
    @events = @q.result(search_params)
    @hashtags = Hashtag.last(10).pluck(:name)
    @day_searched = change_to_timeclass(search_params[:start_date_lteq_all])

    if search_params[:categories_id_eq] == ""
      @keyword = "全"
    else
      cat_index = @categories.ids.index(search_params[:categories_id_eq].to_i)
      @keyword = @categories[cat_index].name
    end

    today = Time.now

    gon.events = @events.map do | event |
      {
        'event':event,
        'categories':event.categories.pluck(:name),
        'date':"#{event.start_date.strftime("%Y年%m月%d日")} ~ #{event.end_date.strftime("%Y年%m月%d日")}",
        'countdate':"#{((event.end_date - today )/60/60/24).ceil if @day_searched.strftime('%Y%m%d') == today.strftime('%Y%m%d')}"
      }
    end

    render :index
  end

  def new
    @event = Event.new(latlng_params)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @event = current_user.events.build(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to mypage_user_path(current_user.id)}
        format.js {
          flash[:notice] = "新しいイベントを投稿しました"
          render js: "window.location = '#{posts_index_user_path(current_user.id)}' " }
      else
        format.js
      end
    end
  end

  def show
    @comments = @event.comments.all.order(created_at: "DESC")
    if user_signed_in?
      @comment = current_user.comments.build(event_id: params[:id])
      @favorite = current_user.favorites.find_by(event_id: @event.id)
    end
    respond_to do |format|
      format.js
    end
  end

  def edit
    gon.event = @event
    respond_to do |format|
      format.js
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to posts_index_user_path(current_user.id),notice:"イベント内容を変更しました" }
        format.js {
          flash[:notice] = "イベント情報を更新しました"
          render js: "window.location = '#{posts_index_user_path(current_user.id)}' " }
      else
        format.js
      end
    end
  end

  def destroy
    if @event.destroy
      redirect_to events_path, notice:"イベントを削除しました"
    else
      redirect_to event_path(@event)
    end
  end

  def hashtag
    @q = Event.ransack(params[:q])
    @categories = Category.all
    @hashtags = Hashtag.last(10).pluck(:name)
    @hashtag = Hashtag.find_by(name: params[:name])
    @events = @hashtag.events.where("start_date <= ?", Time.now).where("end_date >= ?", Time.now)
    today = Time.now
    gon.events = @events.map do | event |
        {
        'event':event,
        'categories':event.categories.pluck(:name),
        'date':"#{event.start_date.strftime("%Y年%m月%d日")} ~ #{event.end_date.strftime("%Y年%m月%d日")}", 'countdate':"#{((event.end_date - today )/60/60/24).ceil }"
        }
    end

    @day_searched = today
    @keyword = "##{@hashtag.name}"

    render :index
  end

  private
  def event_params
    params.require(:event).permit(:title, :description, :location, :start_date, :end_date, :official_page, :image, :latitude, :longitude, :image_cache, category_ids:[])
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def search_params
    params.require(:q).permit!
  end

  def latlng_params
    params.permit(:latitude,:longitude)
  end

  def change_to_timeclass(day)
    day = Time.now.strftime("%Y-%m-%d") if day == ""
    arr = day.split("-").map(&:to_i)
    Time.mktime(arr[0],arr[1],arr[2])
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def render_with_hashtags(description)
    description.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/){ |tag| link_to tag, "/events/hashtag/#{tag.delete('/[#＃]/')}", class:"hashtag"}.html_safe
  end

  def choose_new_or_edit
    if action_name == 'new'
      events_path
    elsif action_name == 'edit'
      event_path
    end
  end
end

app/views/events/_detail.html.erb
<div class="detail-modal container-fluid m-0 p-0 position-relative">
  <div class="close-btn">
    <span></span>
    <span></span>
  </div>
  <% if @event.user.image.present? %>
    <%= image_tag @event.user.image.url, class:"avatar-m" %>
  <% else %>
    <%= image_tag 'default_avatar.png', class:"avatar-m" %>
  <% end %>
  <span><%= @event.user.name %>さんが投稿したイベントです!</span>
  <div class="row m-0 p-0 justify-content-start">

    <div class="col-12 col-sm-auto p-0">
      <div id="mapid2"></div>
    </div>

    <div class="col-12 col-sm-12 overflow-wrap p-0">
      <div class="event-image">
        <% if @event.image.present? %>
          <%= image_tag @event.image.url %>
        <% end %>
      </div>
      <div class="mt-4 mx-4">
        <h1><%= @event.title %></h1><span id="favorite_area"><%= render 'favorites/favorite', { favorite: @favorite, event: @event} %></span>
      </div>
      <div class="mx-4">
        <% @event.categories.each do | category | %>
          <span class="category"><%= category.name %></span>
        <% end %>
      </div>
      <div class="mt-1 mx-4">
        <span class="note">開催場所：<%= @event.location %></span>
      </div>
      <div class="mt-1 mx-4">
        <span class="note">開催期間：<%= l @event.start_date, format: :date %> ~ <%= l @event.end_date, format: :date %></span>
      </div>
      <div class="mt-2 mx-4">
        <%= render_with_hashtags(@event.description) %>
      </div>

      <div class="official-page mt-2 mx-4">
        <% if @event.official_page.present? %>
          <%= link_to @event.official_page, target:"_blank" do %>
            <i class="fas fa-link"></i>WEBサイト
          <% end %>
        <% end %>
        <span id="route" onClick=""><i class="fas fa-external-link-alt"></i>経路</span>
        <%= link_to "https://www.google.com/calendar/render?action=TEMPLATE&text=#{@event.title}&dates=#{l @event.start_date, format: :gcal}/#{l @event.end_date, format: :gcal}&location=#{@event.location}&details=#{@event.official_page if @event.official_page.present?}", target: :_blank do %>
          <i class="fas fa-external-link-alt"></i>Googleカレンダーに登録
        <% end %>
      </div>
      <div class="mx-4">
        <% if user_signed_in? %>
          <div class="text-right">
            <% if @event.user == current_user %>
              <%= link_to t('view.edit'), edit_event_path(@event),remote: true,class:"link-inshow" %>
              <%= link_to t('view.destroy'), event_path(@event), method: :delete,class:"link-inshow" %>
            <% end %>
          </div>

          <div id="comment-form">
            <%= form_with( model: comment, remote: true) do |f| %>
              <div class="mt-3">
                <%= f.label :content,t('view.comment.post') %><br>
                <%= f.text_area :content,class:"comment-form",maxlength:"260" %>
                <%= f.hidden_field :event_id, value: comment.event_id %>
                  <div id="comment-error" class="mt-0"></div>
              </div>
              <div class="text-right">
                <%= f.submit t('view.post') ,class:"btn-inshow" %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
      <div id="comments_index" class="mx-4">
        <%= render 'comments/index', { comments: @comments} %>
      </div>
    </div>

  </div>
</div>

<div id="mask" class="hidden"></div>
<%= javascript_include_tag 'event_show' %>

app/views/events/_form.html.erb
<div class="modal-wrapper container p-0">
  <div class="close-btn">
    <span></span>
    <span></span>
  </div>
  <% if action_name == 'edit' %>
    <div id="mapid3" class="row" style="width:100%; height:150px; margin:0;"></div>
    <p class="note text-center">※地図をドラッグしてマーカー位置を調整できます</p>
  <% end %>
  <div class="row row-cols-1 p-4">
    <div class="col">
      <%= form_with( model: event, url:choose_new_or_edit,remote: true ) do |f| %>

      <div class="container p-4 mt-1">
        <div id="event-messages" class="row"></div>
        <div class="row p-0 m-0 align-items-center  justify-content-center">
          <div class="col-12 col-sm-8 p-0 mx-0 mb-1">
            <div class="container p-0 m-0">
              <div class="row mb-1">
                <div class="col-3 text-right px-0">
                  <%= f.label :title, t('view.event.title') %><span class="must-need">*<span>
                </div>
                <div class="col-9 pr-0">
                  <%= f.text_field :title ,placeholder:t('view.event.title') ,required:"required" %>
                </div>
              </div>
              <div class="row mb-1">
                <div class="col-3 text-right px-0">
                  <%= f.label :location, t('view.event.location') %><span class="must-need">*<span>
                </div>
                <div class="col-9 pr-0 mt-1">
                  <%= f.text_field :location,placeholder:t('view.event.location'),required:"required" %>
                </div>
              </div>
              <div class="row mb-2">
                <div class="col-3 text-right px-0">
                  <%= f.label :start_date, t('view.event.start_date') %><span class="must-need">*<span>
                </div>
                <div class="col-9 pr-0 mt-1">
                  <% if action_name == "new" %>
                    <%= f.date_field :start_date,value:Time.now.strftime("%Y-%m-%d"), class:"calender" %>
                  <% else %>
                    <%= f.date_field :start_date, class:"calender" %>
                  <% end %>
                </div>
              </div>
              <div class="row mb-2">
                <div class="col-3 text-right px-0">
                  <%= f.label :end_date, t('view.event.end_date') %><span class="must-need">*<span>
                </div>
                <div class="col-9 pr-0">
                  <% if action_name == "new" %>
                    <%= f.date_field :end_date ,value:Time.now.since(7.days).strftime("%Y-%m-%d"),class:"calender" %>
                  <% else %>
                    <%= f.date_field :end_date, class:"calender" %>
                  <% end %>
                </div>
              </div>
              <div class="row mb-1">
                <div class="col-3 text-right px-0">
                  <%= f.label :official_page, t('view.event.official_page') %>
                </div>
                <div class="col-9 pr-0">
                  <%= f.url_field :official_page, placeholder:t('view.event.official_page'),placeholder:"https://" %>
                </div>
              </div>
            </div>
          </div>
          <div class="col-12 col-sm-4 p-0 m-0 text-center">
            <div class="field">
              <%= f.label :image, t('view.event.image'), for:"event_post_image" %><br />
              <label>
                <div class="event-image-area">
                  <%= f.file_field :image , id:"event-post-image" %>
                    <div class="choice-box">
                      ＋
                    </div>
                    <div class="current-image">
                      <% if event.image.present? %>
                        <%= image_tag event.image.url, class:"event-image" %>
                      <% end %>
                    </div>
                </div>
              </label>
            </div>
          </div>
        </div>

        <div class="row mb-1">
          <div class="col-2 text-nowrap text-right px-0">
            <%= f.label :description, t('view.event.description') %><span class="must-need">*<span>
          </div>
          <div class="col-10 pr-0">
            <%= f.text_area :description,placeholder:"イベントの詳しい内容",required:"required" ,class:"description-form"%>
          </div>
        </div>

        <div class="row mb-1">
          <div class="col-2 text-right px-0">
              <label><%= t('view.category') %></label><span class="must-need">*</span><br>
              <span class="note">(※複数可)</span>
          </div>
          <div class="col-10 category-input">
            <% Category.all.each do |category| %>
             <%= f.check_box :category_ids, { multiple: true }, category[:id], nil %>
             <%= f.label :category_ids, category.name, value: category[:id] %>
            <% end %>
          </div>
        </div>
        <div class="text-center my-3">
          <%= f.hidden_field :latitude , id:"latitude" %>
          <%= f.hidden_field :longitude , id:"longitude" %>
          <%= f.submit t('view.post'),class:"submit-btn px-5" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>
<script>
  $(function(){
    $('#event-post-image').change(function(){
      console.log('change');
      $('.event-image').remove();
      var file = $(this).prop('files')[0];
      if(!file.type.match('image.*')){
        return;
      }
      var fileReader = new FileReader();
      fileReader.onloadend = function() {
        $('.current-image').html('<img src="' + fileReader.result + '" style="width:150px; height:150px; object-fit:cover;"/>');
        $('.choice-box').css('opacity','0');
      }
      fileReader.readAsDataURL(file);
    });
  });
</script>
<% if action_name == 'edit' %>
  <%= javascript_include_tag 'events_form' %>
<% end %>

app/views/events/_messages.html.erb
<% if event.errors.any? %>
 <div id="error_explanation">
   <% event.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
   <% end %>
 </div>
<% end %>

app/views/events/_serch_form.html.erb
<div class="search_form module p-2">
  <i class="fas fa-search-location close-search-btn"></i>
  <h5>イベント検索</h5>
  <%= search_form_for(@q, url:search_events_path) do |f| %>
    <div class="search-wrapper">
      <div class="search-category">
        <div class="mt-2">
          <label>カテゴリーで絞りこむ</label>
        </div>
        <div class="category-input d-flex flex-wrap">
          <%= f.collection_radio_buttons :categories_id_eq, @categories, :id, :name %>
          <%= f.radio_button :categories_id_eq, '', checked: true,id:"q_categories_id_eq" %>
          <%= f.label :categories_id_eq, "指定なし" %>
        </div>
      </div>
      <div class="search-date">
        <div class="mt-2">
          <%= f.label :start_date_lteq_all, t('view.search_by_date') %>
        </div>
        <div class="">
          <%= f.date_field :start_date_lteq_all ,class:"calender", value: Time.now.strftime("%Y-%m-%d")%>
          <%= f.hidden_field :end_date_gteq_all, value: Time.now.strftime("%Y-%m-%d")%>
        </div>
      </div>
    </div>
    <div class="m-3 text-center">
      <%= f.submit class:"action-btn px-5"%>
    </div>
  <% end %>
</div>

app/views/events/create.js.erb
$('#event-messages').html('<%= j( render 'messages', { event: @event }) %>');

app/views/events/edit.html.erb
<h1>イベント編集画面</h1>
<%= render partial:'form',locals: { event: @event } %>

<%= javascript_include_tag 'event_edit' %>

app/views/events/edit.js.erb
$('#edit_event_modal').html('<%= j(render 'form', { event: @event }) %>');

$('#show_event_modal').addClass('hidden');
$('#edit_event_modal').removeClass('hidden');
$('#mask').removeClass('hidden');


$('#mask').on('click',function(){
  $('#edit_event_modal').addClass('hidden');
  $('#mask').addClass('hidden');
});

$('.close-btn').on('click',function(){
  $('#edit_event_modal').addClass('hidden');
  $('#mask').addClass('hidden');
});

app/views/events/index.html.erb
<div id="mask" class="hidden"></div>
<div id="show_event_modal" class="hidden"></div>
<div id="edit_event_modal" class="hidden"></div>
<% if user_signed_in? %>
  <div id="new_event_modal" class="hidden">
  </div>
<% end %>

<div class="map-wrapper p-3">
  <div id="event-header" class="result-message mt-3">
    <% if action_name == 'create' || action_name == 'update' %>
      <%= @event.title %>
    <% else %>
      <% if @day_searched.strftime('%Y%m%d') == Time.now.strftime('%Y%m%d') %>
        <h1>本日開催中の<%= @keyword %>イベント</h1>
      <% else %>
        <h1><%= l @day_searched, format: :date %>に開催中の<%= @keyword %>イベント</h1>
      <% end %>
        <p>マップ上に<%= @events.size %>件のイベントを表示しています。</p>
    <% end %>
  </div>

  <div class="container-fluid my-3">
    <div class="row">
      <div class="col-sm-12 col-md-9 mb-2 space-cols">
        <div id="mapid" class="map-index"></div>
        <div class="m-2"><h5>マップ上の投稿したい地点をクリックをするとイベント投稿フォームが立ち上がります</h5></div>
      </div>
      <div class="col-sm-12 col-md-3 mb-2 space-cols search-module">
        <%= render 'serch_form' %>
        <%= render 'hashtags/index' %>
      </div>
    </div>
  </div>
</div>
<script>
$(function(){
  if(sessionStorage.mapsize === 'map-fullsize'){
    $('#mapid').removeClass('map-index');
    $('#mapid').addClass('map-fullsize');
    $('.space-cols').addClass('fix-bottom');
    $('.close-search-btn').addClass('open btn-fixed');
    expandbtn.state('full-screen-reset');
  }else{
    $('#mapid').removeClass('map-fullsize');
    $('#mapid').addClass('map-index');
    $('.space-cols').removeClass('fix-bottom');
    expandbtn.state('full-screen');
  };
})
</script>


<%= javascript_include_tag 'events_index'%>
<%= javascript_include_tag 'currentposi' %>



<% if user_signed_in? %>
  <%= javascript_include_tag 'event_new' %>
<% else %>
  <%= javascript_include_tag 'prelogin' %>
<% end %>

app/views/events/new.js.erb
$('#new_event_modal').html('<%= j(render 'form', { event: @event }) %>');

$('#new_event_modal').removeClass('hidden');
$('#mask').removeClass('hidden');

$('#mask').on('click',function(){
  $('#new_event_modal').addClass('hidden');
  $('#mask').addClass('hidden');
});

$('.close-btn').on('click',function(){
  $('#new_event_modal').addClass('hidden');
  $('#mask').addClass('hidden');
});

app/views/events/show.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">

  </div>

  <div class="row justify-content-center">
    <div class="col-sm-auto text-left my-3">

      <div class="container">
        <div class="row">
          <div class="col">
            <h1><%= @event.title %></h1>
          </div>
          <div class="col-sm-auto">
            <% @event.categories.each do | category | %>
              <span class="category"><%= category.name %></span>
            <% end %>
          </div>
          <div id="favorite_area" class="col-sm-auto">
            <%= render 'favorites/favorite', { favorite: @favorite, event: @event} %>
          </div>
        </div>
      </div>

    </div>
    <div class="w-100"></div>
    <div class="col-sm-auto">
      <div id="mapid" style="width:400px; height:600px;"></div>

    </div>

    <div class="col-sm-auto">
      <div class="">
        <% if @event.image.present? %>
          <%= image_tag @event.image.url %>
        <% end %>
      </div>
      <div class="">
        <div class="">
          <%= @event.location %>
        </div>
        <div class="">
          <%= render_with_hashtags(@event.description) %>
        </div>
        <div class="">
          <%= raw Rinku.auto_link(@event.official_page,:all,'target="_blank"') %>
        </div>
        <div class="">
          <%= l @event.start_date, format: :date %> ~ <%= l @event.end_date, format: :date %>
        </div>
      </div>
      <% if user_signed_in? %>
        <div class="">
          <% if @event.user == current_user %>
            <%= link_to t('view.edit'), edit_event_path(@event) %>
            <%= link_to t('view.destroy'), event_path(@event), method: :delete %>
          <% end %>
        </div>

        <div class="">
          <%= link_to 'コメントを作成', new_comment_path(event_id: @event.id), remote:true %>
        </div>
      <% end %>
      <div id="comments" class="">
        <% if user_signed_in? %>
          <div id="comment_modal" class="hidden">
            <%= render 'comments/form', { comment: @comment } %>
          </div>
        <% end %>
        <div id="comments_index" class="">
          <%= render 'comments/index', { comments: @comments} %>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="mask" class="hidden"></div>
<%= javascript_include_tag 'event_show' %>

app/views/events/show.js.erb
$('#show_event_modal').html('<%= j(render 'detail', { event: @event, comment:@comment }) %>');

$('#show_event_modal').removeClass('hidden');
$('#mask').removeClass('hidden');

$('#mask').on('click',function(){
  $('#show_event_modal').addClass('hidden');
  $('#mask').addClass('hidden');
});

$('.close-btn').on('click',function(){
  $('#show_event_modal').addClass('hidden');
  $('#mask').addClass('hidden');
});

$('#route').attr('onClick', `openSearchRoute(${Number(markerPosi[0])},${Number(markerPosi[1])})`);

app/views/events/update.js.erb
$('#event-messages').html('<%= j( render 'messages', { event: @event }) %>');