config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'events#index'
  devise_for :users,controllers:{
    registrations: "users/registrations",
    sessions: 'users/sessions',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    post 'users/guest_sign_in', to:'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to:'users/sessions#guest_admin_sign_in'
  end
  resources :users do
    resources :mylocations, only:[:new, :create, :destroy]
    member do
      get :mypage
      get :posts_index
    end
  end
  resources :events do
    collection do
      get '/hashtag/:name', to:'events#hashtag'
      get 'search', to:'events#search'
    end
  end
  resources :comments, only:[:index, :create, :destroy]
  resources :favorites, only:[:create,:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NOW ON MAP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= include_gon %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>

    <meta name="viewport" content="width=device-width">
  </head>

  <body>
    <header>
      <div id="hamburger">
        <div class="btn-gNav">
          <span></span>
          <span></span>
          <span></span>
        </div>
        <%= link_to image_tag("logo.png"), events_path,id:"logo" %>
          <nav id="gNav" class="">
            <ul class="gNav-menu">
              <li class="menu-item"><%= link_to t('view.event.index'), events_path %>
              </li>
              <% if user_signed_in? %>
                <li class="menu-item"><%= link_to t('view.mypage'), mypage_user_path(current_user.id) %></li>
                <li class="menu-item"><%= link_to t('view.log_out'), destroy_user_session_path, method: :delete %></li>
                <li class="menu-item"><%= link_to t('view.user_info'),edit_user_registration_path %></li>
              <% else %>
                <li class="menu-item"><%= link_to t('view.sign_in'), new_user_session_path %></li>
                <li class="menu-item"><%= link_to 'ゲストログイン(一般)', users_guest_sign_in_path,method: :post %></li>
                <!-- <li class="menu-item"><%= link_to 'ゲストログイン(管理者)', users_guest_admin_sign_in_path, method: :post %></li> -->
              <% end %>
              <div class="mr-2 py-1 px-2 position-relative help">
                <a href="#" id="introduction-pop" class="help-button">?</a>
                <span class="help-description">
                  NOW ON MAPの使い方を見る
                </span>
              </div>
              <% if user_signed_in? %>
                <div class="mr-2 py-1 px-2">
                  <%= link_to edit_user_registration_path do %>
                    <% if current_user.image.present? %>
                      <% image_tag current_user.image.url, class:"avatar-m" %>
                    <% else %>
                      <%= image_tag 'default_avatar.png', class:"avatar-m" %>
                    <% end %>
                  <% end %>
                </div>
              <% else %>
                <div class=""></div>
              <% end %>
            </ul>
          </nav>
      </div>
    </header>

    <div id="content-area">
      <div class="spacing-header">
      </div>
      <% if notice  %>
        <div class="notice p-1">
          <p class="notice-content"><%= notice %></p>
        </div>
      <% end %>
      <% if alert %>
        <div class="notice p-1">
          <p><%= alert %></p>
        </div>
      <% end %>
      <%= yield %>
    </div>


    <div id="introduction-modal" class="hidden p-0 slider">
      <div class="slides">
        <div class="slide-item">
          <div class="slide-content text-center">
            <div class="my-3">
              <h1>NOW ON MAPとは?</h1>
            </div>
            <div>
              <p>地図からイベント情報を投稿・発見できるWEBアプリです。</p>
              <p>「今日近くで何かやってないかな？」</p>
              <p>「地域の人にイベントを知らせたい」</p>
              <p>などなど、地図を介したイベントのPRや旅行先でのイベント探しなど、あなたに合った使い方を探してみてください。</p>
            </div>
            <% if user_signed_in? %>
            <% else %>
              <div class="my-5">
                <%= link_to t("view.sign_in"), new_user_session_path, class:"link-btn" %>
                <%= link_to t("view.sign_up"), new_user_registration_path,class:"link-btn" %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="slide-item">
          <div class="slide-content">
            <div class="text-center my-3">
              <h2>カテゴリーと日付からイベントを探せます</h2>
            </div>
            <div class="content">
              <div class="text-left">
                <p>カテゴリーと日付を選択すると、その日に開催中のイベントが地図に表示されます。</p>
                <div class="gif-image">
                  <img src="/imgs/slide2.gif" alt="gif-image">
                </div>
                <p>地図上のマーカーをクリックして表示するポップアップから、イベントの詳細を表示できます。</p>
                <p>イベントのハッシュタグをクリックすると、同じハッシュタグの付いたイベント一覧が表示されます。</p>
              </div>
            </div>
          </div>
        </div>
        <div class="slide-item">
          <div class="slide-content">
            <div class="text-center my-3">
              <h2>地図をクリックすると<br>
                その場所にイベントを投稿できます</h2>
            </div>
            <div class="content">
              <div class="text-left">
                <p class="must-need">*ログインが必要です</p>
                <p>投稿したい場所をクリックするとポップアップが表示され、そこからイベント投稿フォームを表示できます。</p>
                <div class="gif-image">
                  <img src="/imgs/slide3.gif" alt="gif-image">
                </div>
                <p>投稿したイベントはマイページから確認することができます。</p>
              </div>
            </div>
          </div>
        </div>
        <div class="slide-item">
          <div class="slide-content">
            <div class="text-center my-3">
              <h2>イベント情報にはコメントを残せます</h2>
            </div>
            <div class="content">
              <div class="align-middle">
                <p class="must-need">*ログインが必要です</p>
                <p>イベント詳細画面のフォームからコメントを投稿することができます。感想や疑問など何でもコメントしてみてください。</p>
                <div class="gif-image">
                  <img src="/imgs/slide4.gif" alt="gif-image">
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="slide-item">
          <div class="slide-content">
            <div class="text-center my-3">
              <h2>お気に入りしたイベントは<br>
                マイページで表示できます</h2>
            </div>
            <div class="content">
              <div class="align-middle text-left">
                <p class="must-need">*ログインが必要です</p>
                <p>イベント詳細のハートマークをクリックするとお気に入りに登録することができます。</p>
                <div class="gif-image">
                  <img src="/imgs/slide5.gif" alt="gif-image">
                </div>
                <p>お気に入りしたイベントは、「マイページ」の「気になった投稿一覧」をクリックすると地図に表示されます。</p>
              </div>
            </div>
          </div>
        </div>
        <div class="slide-item">
          <div class="slide-content">
            <div class="text-center my-3">
              <h2>よく使う場所を登録しておくことで<br>
                ワンクリックで遷移できます</h2>
            </div>
            <div class="content">
              <div class="align-middle text-left">
                <p class="must-need">*ログインが必要です</p>
                <p>マイページではよく使う場所を「マイロケーション」として登録しておくことができます。よく使う場所を登録しておくと便利です。</p>
                <div class="text-center gif-image2">
                  <img src="/imgs/slide6.gif" class="d-inline-block" alt="image-gif">
                  <img src="/imgs/slide7.gif" class="d-inline-block" alt="image-gif">
                </div>
                <p>マイロケーションに登録されたボタンをクリックすると、地図が登録地点にジャンプします。</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


    <footer>
      <div>
        <div id="qrcode">
          <img src="/imgs/QR_607151.png" alt="qrcode">
          <p>こちらを読み取るとスマホでご覧になれます</p>
        </div>
        <p class="text-center">
          © 2021 Now On Map All rights reserved.
        </p>
      </div>
    </footer>

    <script>
        $('#introduction-pop').on('click',function(){
          $('#introduction-modal').removeClass('hidden');
          $('#mask').removeClass('hidden');
        });

        $('#mask').on('click',function(){
          $('#introduction-modal').addClass('hidden');
          $('#mask').addClass('hidden');
          var date = new Date();
          // date.setTime( date.getTime() + 60 * 1000 )
          $.cookie('Flg','on', { expires: 1, path: '/' } );
          console.log('初めてのご訪問ありがとうございます！')
        });

        $(function() {
        	$('.btn-gNav').on("click", function(){
        		$(this).toggleClass('open');
        		$('#gNav').toggleClass('open');
        	});
        });

        $(function() {
            $('.slides').slick({
                dots: true,
                allows: true,
            });
        });

        $(function(){
          if($.cookie('Flg') == 'on'){
          }else{
            $('#introduction-modal').removeClass('hidden');
            $('#mask').removeClass('hidden');
          }
        });
    </script>
  </body>
</html>